<?php
/*
Plugin Name: Postform Integration for Contact Form 7
Description: Postform is a back-end platform for HTML forms that allows you to collect submissions and integrate with apps you already use. With this plugin, you can use Postform to process and save submissions from Contact Form 7.
Author: Postform
Author URI: https://postform.com
Text Domain: postform-for-contact-form-7
Version: 1.0.0
*/

class Postform_Integration_For_Contact_Form_7 {

  private const POSTFORM_ACTION_URL_PROP = 'postform_action_url';

  public function __construct() {
    add_action( 'wpcf7_config_validator_validate', array( $this, 'validate_properties' ) );
    add_action( 'wpcf7_save_contact_form', array( $this, 'save_properties' ) );
    add_filter( 'wpcf7_contact_form_properties', array( $this, 'filter_properties' ) );
    add_filter( 'wpcf7_editor_panels', array( $this, 'filter_panels' ) );
    add_filter( 'wpcf7_form_action_url', array( $this, 'get_form_action_url' ) );
    add_filter( 'wpcf7_load_js', '__return_false' );
  }

  /**
   * Adds custom panel to edit page
   */
  public function filter_panels( $panels ) {
    $panels['postform-panel'] = array(
      'title' => 'Postform',
      'callback' => array( $this, 'panel_content' )
    );
    return $panels;
  }

  /**
   * Specify custom properties so that we can utilize core code to save values
   */
  public function filter_properties( $properties ) {
    if ( ! array_key_exists( self::POSTFORM_ACTION_URL_PROP, $properties ) ) {
      $properties[ self::POSTFORM_ACTION_URL_PROP ] = '';
    }
    return $properties;
  }

  /**
   * Returns the Postform action URL for the current form
   */
  public function get_form_action_url( $default_url ) {
    $contact_form = WPCF7_ContactForm::get_current();
    $postform_action_url = $contact_form->prop( self::POSTFORM_ACTION_URL_PROP );

    if ( $this->is_valid_action_url( $postform_action_url ) ) {
      return $postform_action_url;
    }

    return $default_url;
  }

  /**
   * Content to display in the custom panel. This will allow the user to input
   * their Postform action URL.
   */
  public function panel_content( $post ) {
    ?>
    <h2><?php echo esc_html(  __( 'Postform', 'postform-for-contact-form-7' ) ); ?></h2>
    <fieldset>
      <legend>
        <?php
          $description = __(
            "To integrate this form, enter the endpoint generated by Postform below. For more details, see <a href=\"https://postform.com/docs/getting-started/integrating-your-form\" target=\"_blank\">Postform docs</a>.",
            'postform-for-contact-form-7'
          );
          echo $description;
          echo '<br />';
        ?>
      </legend>
      <table class="form-table">
        <tbody>
          <tr>
            <th scope="row">
              <label for="<?php echo esc_attr( self::POSTFORM_ACTION_URL_PROP ); ?>">
                <?php echo esc_html( __( 'Form Endpoint', 'postform-for-contact-form-7' ) ); ?>
              </label>
            </th>
            <td>
              <input type="text" id="<?php echo esc_attr( self::POSTFORM_ACTION_URL_PROP ); ?>" name="<?php echo esc_attr( self::POSTFORM_ACTION_URL_PROP ); ?>" size="40" value="<?php echo esc_attr( $post->prop( self::POSTFORM_ACTION_URL_PROP ) ); ?>" data-config-field="<?php echo esc_attr( self::POSTFORM_ACTION_URL_PROP ); ?>" placeholder="https://postform.com/s/FORM_ID" />
              <p class="description">Enter the endpoint generated by Postform</p>
            </td>
          </tr>
        </tbody>
      </table>
    </fieldset>
    <?php
  }

  /**
   * Add support for saving custom properties
   */
  public function save_properties( $contact_form ) {
    if ( isset( $_POST[ self::POSTFORM_ACTION_URL_PROP ] ) ) {
      $postform_action_url = esc_url_raw( $_POST[ self::POSTFORM_ACTION_URL_PROP ], array( 'https' ) );

      $properties = array();
      $properties[ self::POSTFORM_ACTION_URL_PROP ] = $postform_action_url;

      $contact_form->set_properties( $properties );
    }
  }

  /**
   * Validate the Postform action URL
   */
  public function validate_properties( $validator ) {
    $postform_action_url = $validator->contact_form()->prop( self::POSTFORM_ACTION_URL_PROP );

    if ( ! $this->is_valid_action_url( $postform_action_url ) ) {
      $validator->add_error(
        self::POSTFORM_ACTION_URL_PROP,
        '',
        array(
          'message' => __( "Invalid Postform endpoint URL", 'postform-for-contact-form-7' ),
        )
      );
    }
  }

  /**
   * Returns true if the given url is a valid Postform endpoint
   */
  private function is_valid_action_url( $url ) {
    return ! empty( $url ) && wp_http_validate_url( $url ) != false && strpos( $url, 'https://postform.com/s/', 0 ) === 0;
  }

}

new Postform_Integration_For_Contact_Form_7();
